name: Create the DEB

permissions:
  contents: write

on:
  push:
    branches: [master]

  pull_request:
    types: [opened, reopened, synchronize]
  release:
    types: [published]

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "REPO"

      - name: Copy script files around to stop .github from being added to the package then build the package
        run: |
          mkdir PKG_SOURCE
          cp -Rf REPO/usr REPO/DEBIAN PKG_SOURCE
          dpkg-deb --build PKG_SOURCE ${GITHUB_REPO_NAME}.deb

      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: ${GITHUB_REPO_NAME}.deb
