name: Create the DEB

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "REPO"

      - name: Copy script files around to stop .github from being added to the package then build the package
        run: |
          mkdir PKG_SOURCE
          cp -Rf REPO/usr REPO/DEBIAN PKG_SOURCE
          sed -i 's/^Package: .*/Package: ${GITHUB_REPO_NAME}/' PKG_SOURCE/DEBIAN/control
          sed -i 's/^Version: .*/Version: ${GITHUB_REF#refs/tags/v}/' PKG_SOURCE/DEBIAN/control
          dpkg-deb --build PKG_SOURCE ${GITHUB_REPO_NAME}.deb

      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: ${GITHUB_REPO_NAME}.deb
