name: Create the DEB

permissions:
  contents: write

on:
  push:
    branches: [master]

  pull_request:
    types: [opened, reopened, synchronize]
  release:
    types: [published]

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy script files around to stop .github from being added to the package then build the package
        run: |
          mkdir PKG_SOURCE
          cp -Rf usr DEBIAN PKG_SOURCE
          dpkg-deb --build PKG_SOURCE geossh.deb

      - name: Purge old build
        continue-on-error: true
        run: gh release delete continuous --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Very important stage
        continue-on-error: true
        run: |
          sleep 20s
      - name: Push new build
        run: gh release create continuous --generate-notes --prerelease --title "Continuous Build" *.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
